---
title: "Effect size calculation - Force manuscript"
output: pdf_document
date: "2024-07-01"
---

```{r load_libraries, include=FALSE}

# set current directory to /analysis
library(tidyverse)
library(magrittr)
library(R.matlab)
library(lme4)
library(lmerTest)
library(car)
library(broom)
library(afex)
library(effectsize)


```


## Load data
```{r load_data, echo=FALSE}


# data_path <- '/home/rodrigo/labo/proyectos/fuerza/manuscrito/repositorio/data/'
data_path <- '../data/'
condition_colnames <- c('Normal-NoFBK','Normal-WithFBK','High-NoFBK','High-WithFBK')
subject_df <- data.frame(c(c(1:22),c(1:22),c(23:44),c(23:44)))
colnames(subject_df) <- 'Subject'
levels_A <- c('Normal','High')
levels_F <- c('NoFBK','WithFBK')

# SDA data
data_sda_df <- data.frame(readMat(paste0(data_path,'STDASY.mat')))
colnames(data_sda_df) <- condition_colnames
data_sda_df <- data_sda_df %>%
		pivot_longer(names(.), names_to=c('Attention','Feedback'),
					 names_sep='-', values_to='SDA',
					 cols_vary='slowest')
data_sda_df$Attention <- factor(data_sda_df$Attention, levels=levels_A)
data_sda_df$Feedback <- factor(data_sda_df$Feedback, levels=levels_F)
data_sda_df <- cbind(subject_df, data_sda_df %>% arrange(Attention,Feedback))

# F data
data_f_df <- data.frame(readMat(paste0(data_path,'F1.mat')))
colnames(data_f_df) <- condition_colnames
data_f_df <- data_f_df %>%
		pivot_longer(names(.), names_to=c('Attention','Feedback'),
					 names_sep='-', values_to='F',
					 cols_vary='slowest')
data_f_df$Attention <- factor(data_f_df$Attention, levels=levels_A)
data_f_df$Feedback <- factor(data_f_df$Feedback, levels=levels_F)
data_f_df <- cbind(subject_df, data_f_df %>% arrange(Attention,Feedback))

# SDF data
data_sdf_df <- data.frame(readMat(paste0(data_path,'STDF1.mat')))
colnames(data_sdf_df) <- condition_colnames
data_sdf_df <- data_sdf_df %>%
		pivot_longer(names(.), names_to=c('Attention','Feedback'),
					 names_sep='-', values_to='SDF',
					 cols_vary='slowest')
data_sdf_df$Attention <- factor(data_sdf_df$Attention, levels=levels_A)
data_sdf_df$Feedback <- factor(data_sdf_df$Feedback, levels=levels_F)
data_sdf_df <- cbind(subject_df, data_sdf_df %>% arrange(Attention,Feedback))

# CVF data
data_cvf_df <- data.frame(readMat(paste0(data_path,'CVF1INTRA.mat')))
colnames(data_cvf_df) <- condition_colnames
data_cvf_df <- data_cvf_df %>%
		pivot_longer(names(.), names_to=c('Attention','Feedback'),
					 names_sep='-', values_to='CVF',
					 cols_vary='slowest')
data_cvf_df$Attention <- factor(data_cvf_df$Attention, levels=levels_A)
data_cvf_df$Feedback <- factor(data_cvf_df$Feedback, levels=levels_F)
data_cvf_df <- cbind(subject_df, data_cvf_df %>% arrange(Attention,Feedback))

# MSJ data
data_msj_df <- data.frame(readMat(paste0(data_path,'MSJ.mat')))
colnames(data_msj_df) <- condition_colnames
data_msj_df <- data_msj_df %>%
		pivot_longer(names(.), names_to=c('Attention','Feedback'),
					 names_sep='-', values_to='MSJ',
					 cols_vary='slowest')
data_msj_df$Attention <- factor(data_msj_df$Attention, levels=levels_A)
data_msj_df$Feedback <- factor(data_msj_df$Feedback, levels=levels_F)
data_msj_df <- cbind(subject_df, data_msj_df %>% arrange(Attention,Feedback))


# join SDA, F, SDF, CVF, MSJ
data_df <- list(data_sda_df, data_f_df, data_sdf_df, data_cvf_df, data_msj_df) %>%
				reduce(inner_join, by = join_by(Subject, Attention, Feedback)) %>%
				# create variables for afex and effectsize
				mutate(CVF_center = CVF-mean(CVF),
					   F_center = F-mean(F),
					   Finv = 1/F,
					   Finv_center = Finv-mean(Finv),
					   lognormF = log(F/max(F)),
					   lognormMSJ = log(MSJ/max(MSJ)),
					   lognormF_center = lognormF-mean(lognormF),
					   Subject_aov = row_number()) # between subjects for aov_4


```


### Fit models and compute effect sizes
```{r SDAvsCVF_fit_model, echo=FALSE}


# SDA vs CVF
model_SDACVF <- aov_4(SDA ~ CVF_center + Attention + Feedback
						+ CVF_center:Attention + CVF_center:Feedback + Attention:Feedback
						+ (1|Subject_aov),
						data = data_df,
						covariate = 'CVF_center',
						observed = c('CVF_center'),
						factorize = FALSE,
						anova_table = list(es=c("ges","pes"), sig_symbols=rep("",4)))
model_SDACVF_etap <- eta_squared(model_SDACVF, partial=TRUE, alternative='two.sided')
model_SDACVF_etag <- eta_squared(model_SDACVF, generalized=TRUE, alternative='two.sided')
print(model_SDACVF_etap)
print(model_SDACVF_etag)


## SDF vs F
model_SDFF <- aov_4(SDF ~ F_center + Attention + Feedback
						+ F_center:Attention + F_center:Feedback + Attention:Feedback
						+ (1|Subject_aov),
						data = data_df,
						covariate = 'F_center',
						observed = c('F_center'),
						factorize = FALSE,
						anova_table = list(es=c("ges","pes"), sig_symbols=rep("",4)))
model_SDFF_etap <- eta_squared(model_SDFF, partial=TRUE, alternative='two.sided')
model_SDFF_etag <- eta_squared(model_SDFF, generalized=TRUE, alternative='two.sided')
print(model_SDFF_etap)
print(model_SDFF_etag)


## CVF vs 1/F
model_CVFF <- aov_4(CVF ~ Finv_center + Attention + Feedback
						+ Finv_center:Attention + Finv_center:Feedback + Attention:Feedback
						+ (1|Subject_aov),
						data = data_df,
						covariate = 'Finv_center',
						observed = c('Finv_center'),
						factorize = FALSE,
						anova_table = list(es=c("ges","pes"), sig_symbols=rep("",4)))
model_CVFF_etap <- eta_squared(model_CVFF, partial=TRUE, alternative='two.sided')
model_CVFF_etag <- eta_squared(model_CVFF, generalized=TRUE, alternative='two.sided')
print(model_CVFF_etap)
print(model_CVFF_etag)


## MSJ vs F
model_MSJF <- aov_4(lognormMSJ ~ lognormF_center + Attention + Feedback
						+ lognormF_center:Attention + lognormF_center:Feedback + Attention:Feedback
						+ (1|Subject_aov),
						data = data_df,
						covariate = 'lognormF_center',
						observed = c('lognormF_center'),
						factorize = FALSE,
						anova_table = list(es=c("ges","pes"), sig_symbols=rep("",4)))
model_MSJF_etap <- eta_squared(model_MSJF, partial=TRUE, alternative='two.sided')
model_MSJF_etag <- eta_squared(model_MSJF, generalized=TRUE, alternative='two.sided')
print(model_MSJF_etap)
print(model_MSJF_etag)




```

